### ISSUE TITLE
xEdit Quick Auto Clean Reports

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#292]
Checked if added to Master List. 
Strikeout if addition is not required.
Links are to reports below.

---
- [x]  [DLC](https://github.com/loot/skyrimse/issues/292#issuecomment-423271332)
---
  - [x]   [Eli's Breezehome Overhaul](https://github.com/loot/skyrimse/issues/292#issuecomment-423272240)
---
- [x] [The Haven From The Cold And Dark 2.0](https://github.com/loot/skyrimse/issues/292#issuecomment-423273456)
---
- [x] [Interesting NPCs](https://github.com/loot/skyrimse/issues/292#issuecomment-423278686)
---
- [x] [Holds The City Overhaul](https://github.com/loot/skyrimse/issues/292#issuecomment-423283352)
---
- [x] [Beyond Skyrim - Bruma SE](https://github.com/loot/skyrimse/issues/292#issuecomment-423286985)
---
- [x] [Rigmor of Bruma](https://github.com/loot/skyrimse/issues/292#issuecomment-423288726)
---
- [x] [Palaces and Castles Enhanced SSE](https://github.com/loot/skyrimse/issues/292#issuecomment-423295128)
---
- [x] [VIGILANT SE](https://github.com/loot/skyrimse/issues/292#issuecomment-423303685)
---
- [x] [M'rissi's Tails of Troubles SE](https://github.com/loot/skyrimse/issues/292#issuecomment-423305898/)
---
- [x] [Hammet's Dungeon Packs for SE](https://github.com/loot/skyrimse/issues/292#issuecomment-423581425)

**Comment by MacSplody** [comment]
```
 - name: 'Update.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xE95F6A98
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 256
        udr: 91
        nav: 2
    dirty:
      - <<: *dirtyPlugin
        crc: 0xA208CF56
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        nav: 2

  - name: 'Dawnguard.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xCFBEE94B
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 724
        udr: 82
        nav: 57
    dirty:
      - <<: *dirtyPlugin
        crc: 0xC1E55A15
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 3
        nav: 57
    dirty:
      - <<: *dirtyPlugin
        crc: 0xE81631D4
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        nav: 57

  - name: 'Dawnguard.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xE81631D4
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 4
        nav: 57
    dirty:
      - <<: *dirtyPlugin
        crc: 0x63121385
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        nav: 57


Manual clean
CELL 00016BCF: Remove XEZN subrecord referring to RiftenRatwayZone [ECZN:0009FBB9]
CELL 0001FA4C: Wild edit. Remove this record. It's a testing cell.
CELL 0006C3B6: Wild edit. Remove this record. It's a testing cell.

  - name: 'Dawnguard.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x8DB8C71E
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        nav: 57


  - name: 'HearthFires.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x20B605D1
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 211
        udr: 11
        nav: 5
    dirty:
      - <<: *dirtyPlugin
        crc: 0xD5A0679C
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        nav: 5

  - name: 'Dragonborn.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xA1BF01BD
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 81
        udr: 8
        nav: 1
    dirty:
      - <<: *dirtyPlugin
        crc: 0x9E981BAE
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        nav: 1
```

**Comment by MacSplody** [comment]
[Eli's Breezehome Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/2829/)
```
  - name: 'Eli_Breezehome.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x4768B826
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 39
        nav: 2
    dirty:
      - <<: *dirtyPlugin
        crc: 0xCBA83065
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        nav: 2
```

**Comment by MacSplody** [comment]
[The Haven From The Cold And Dark 2.0](https://www.nexusmods.com/skyrimspecialedition/mods/5266)
```
  - name: 'The Haven From The Cold And Dark.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xC53D3A5B
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 3996
        nav: 3
    dirty:
      - <<: *dirtyPlugin
        crc: 0xF54AE822
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        nav: 3
```

**Comment by MacSplody** [comment]
[Interesting NPCs](http://3dnpc.com/2017/11/20/3dnpc-v3-4-for-oldrim-and-sse/)
```
  - name: '3DNPC.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x56EBF1FC
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 331
    clean:
      - crc: 0x35C37E08
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
```

**Comment by MacSplody** [comment]
[Holds The City Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/10609)
```
  - name: 'Holds.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xCECBF47C
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 170
    clean:
      - crc: 0xD7ED6D35
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'

```

**Comment by MacSplody** [comment]
[Beyond Skyrim - Bruma SE](https://www.nexusmods.com/skyrimspecialedition/mods/10917)
```
  - name: 'BSHeartland.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x0B12B4E7
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 488
    clean:
      - crc: 0x72A889E3
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
```

**Comment by MacSplody** [comment]
[Rigmor of Bruma](https://www.nexusmods.com/skyrimspecialedition/mods/5271)
```
  - name: 'Rigmor.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x216656CE
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 378
    clean:
      - crc: 0x7C7A6993
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
[00:00] Quick Clean mode finished.
[01:25] Background Loader: finished
```

**Comment by MacSplody** [comment]
[Palaces and Castles Enhanced SSE](https://www.nexusmods.com/skyrimspecialedition/mods/1819)
```
  - name: 'Palaces Castles Enhanced.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xD291FEF2
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 18
    clean:
      - crc: 0xEBD35943
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
```

**Comment by MacSplody** [comment]
[VIGILANT SE](https://www.nexusmods.com/skyrimspecialedition/mods/11849?tab=description)
```
  - name: 'Vigilant.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x17718ED4
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 52
    clean:
      - crc: 0x9C41B437
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
```

**Comment by MacSplody** [comment]
[M'rissi's Tails of Troubles SE](https://www.nexusmods.com/skyrimspecialedition/mods/9666/)
```
  - name: 'MrissiTailOfTroubles.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x8897007A
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 34
    clean:
      - crc: 0x5EA8DADE
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
```

**Comment by MacSplody** [comment]
[Hammet's Dungeon Packs for SE](https://www.nexusmods.com/skyrimspecialedition/mods/12186)
```
  - name: 'HammetDungeons.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x2B70539B # v1.85
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 21
    clean:
      - crc: 0x34575A8D # v1.85
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'

  - name: 'HammetDungeons.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x8BEF7DAB # v1.86
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'
        itm: 35
    clean:
      - crc: 0x1942CA2C # v1.86
        util: 'SSEEdit v3.2.68 EXPERIMENTAL'

```

**Comment by MacSplody** [comment]
#400
